<?php
error_reporting(-1);
$conf['error_level'] = 2;
ini_set('display_errors', TRUE);
ini_set('display_startup_errors', TRUE);


function recommends_cp_entry_insert($entry) {
  $return_value = NULL;
  try {
    $return_value = db_insert('recommends_cp')
                    ->fields($entry)
                    ->execute();
  }
  catch (Exception $e) {
    drupal_set_message(t('db_insert failed. Message = %message, query= %query',
      array('%message' => $e->getMessage(), '%query' => $e->query_string)), 'error');
  }
  return $return_value;
}


function recommends_cp_entry_update($entry) {
  try {
    // db_update()...->execute() returns the number of rows updated.
    $count = db_update('recommends_cp')
              ->fields($entry)
              ->condition('i_pid', $entry['i_pid'])
              ->condition('i_prof', variable_get('recommends_professor_email'))
              ->execute();
  }
  catch(Exception $e) {
    drupal_set_message(t('db_update failed. Message = %message, query= %query',
      array('%message' => $e->getMessage(), '%query' => $e->query_string)), 'error');
  }
  return $count;
}
/*******************************************************
*
*********************************************************/
function recommends_cp_entry_view($entry) {
  try {
    // db_update()...->execute() returns the number of rows updated.
    $count = db_update('recommends_cp')
              ->fields($entry)
              ->condition('i_pid', $entry['i_pid'])
              ->condition('i_prof', variable_get('recommends_professor_email'))
              ->execute();
  }
  catch(Exception $e) {
    drupal_set_message(t('db_update failed. Message = %message, query= %query',
      array('%message' => $e->getMessage(), '%query' => $e->query_string)), 'error');
  }
  return $count;
}


function recommends_cp_entry_delete($entry) {
  db_delete('recommends_cp')
    ->condition('i_pid', $entry['i_pid'])
    ->condition('i_prof', variable_get('recommends_professor_email'))
    ->execute();

}

function recommends_cp_entry_delete_full($entry) {
  db_delete('recommends_cp')
    ->condition('i_pid', $entry['i_prof'])
    ->condition('i_prof', variable_get('recommends_professor_email'))
    ->execute();

}

function recommends_cp_entry_load($entry = array()) {
  // Read all fields from the recommends_cp table.
  $select = db_select('recommends_cp');
  $select->fields('recommends_cp');
  $select->condition('i_prof', variable_get('recommends_professor_email'));

  // Add each field and value as a condition to this query.
  foreach ($entry as $field => $value) {
    $select->condition($field, $value);
    $select->condition('i_prof', variable_get('recommends_professor_email'));
  }
  // Return the result in object format.
  return $select->execute()->fetchAll();
}

function recommends_cp_entry_load_req($entry = array(),$professor) {
  // Read all fields from the recommends_cp table.
  $select = db_select('recommends_cp');
  $select->fields('recommends_cp');
  $select->condition('i_prof', $professor);

  // Add each field and value as a condition to this query.
  foreach ($entry as $field => $value) {
    $select->condition($field, $value);
    $select->condition('i_prof', variable_get('recommends_professor_email'));
  }
  // Return the result in object format.
  return $select->execute()->fetchAll();
}

function recommends_cp_entry_load_mob($entry = array(),$search,$semester,$year) { 
  // Read all fields from the recommends_cp table.
  $select = db_select('recommends_cp');
  $select->fields('recommends_cp');
   $select->condition('i_course', $search);
    $select->condition('i_semester', $semester);
    $select->condition('i_year', $year);
  $select->condition('i_prof', variable_get('recommends_professor_email'));

  // Add each field and value as a condition to this query.
  foreach ($entry as $field => $value) {
    $select->condition($field, $value);
   
    $select->condition('i_prof', variable_get('recommends_professor_email'));
  }
  // Return the result in object format.
  return $select->execute()->fetchAll();
}

function recommends_cp_entry_load_jst($entry = array(),$course,$semester,$year) {
   
   $select = db_select('recommends_cp', 'c');
    // Select these specific fields for the output.
  $select->addField('c', 'i_pid');
  $select->addField('c', 'i_prof');
  $select->addField('c', 'i_course');
  $select->addField('c', 'i_semester');
  $select->addField('c', 'i_year');
  $select->addField('c', 'i_coursename');
  $select->addField('c', 'i_objective');
  $select->addField('c', 'i_grade_a');
  $select->addField('c', 'i_grade_b');
  $select->addField('c', 'i_grade_other');
  $select->addField('c', 'i_timestamp');
  $select->condition('c.i_course', $course);
  $select->condition('c.i_semester', $semester);
  $select->condition('c.i_year', $year);
  $select->condition('i_prof', variable_get('recommends_student_professor_email'));
  return $select->execute()->fetchAll(PDO::FETCH_ASSOC);
  
}

function recommends_cp_advanced_list() {
  drupal_set_title('Conducted Courses');
  
  $output = '';

   $select = db_select('recommends_cp', 'c');
    // Select these specific fields for the output.
  
  $select->addField('c', 'i_course');
  $select->addField('c', 'i_coursename');
  $select->addField('c', 'i_semester');
  $select->addField('c', 'i_year');
  $select->addField('c', 'i_timestamp');
  $select->condition('i_prof', variable_get('recommends_professor_email'));

  $entries = $select->execute()->fetchAll(PDO::FETCH_ASSOC);
  if (!empty($entries)) {
    $rows = array();
    foreach ($entries as $entry) {
      // Sanitize the data before handing it off to the theme layer.
      $rows[] = array_map('check_plain', $entry);
    }
    // Make a table for them.
    $header = array(  t('Course'), t('Course Name'), t('Semester'),  t('Year'),  t('Timestamp'));
    $output .= theme('table', array('header' => $header, 'rows' => $rows));
  }
  else {
    drupal_set_message(t('No entries in the Course Table.'));
  }
  return $output;
}

/**
 * Implements hook_help().
 *
 * Show some help on each form provided by this module.
 */
function recommends_cp_help($path) {
  $output = '';
  switch ($path) {
    case 'recommendations/recmd_cp/courses':
      break;
    case 'recommendations/recmd_cp/courses/update':
      break;
    case 'recommendations/recmd_cp/courses/add':
      break;
    case 'recommendations/recmd_cp/courses/view':
      break;
    case 'recommendations/recmd_cp/courses/delete':
      break;
  }
  return $output;
}

/**
 * Implements hook_menu().
 *
 * Set up calls to drupal_get_form() for all our example cases.
 */
function recommends_cp_menu() {
  $items = array();

  $items['recommendations/recmd_cp/coursesinstr'] = array(
    'title' => 'Courses Conducted',
    'menu_name' => 'menu-professor',
    'weight' => -8,
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('recommends_cp_form_view'),
    'access callback' => TRUE,
    'expanded' => TRUE,
  );
    $items['recommendations/recmd_cp/coursesinstr/view'] = array(
    'title' => 'View',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('recommends_cp_form_view'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'access callback' => TRUE,
    'weight' => -11,
  );
 
  $items['recommendations/recmd_cp/coursesinstr/add'] = array(
    'title' => 'Add',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('recommends_cp_form_add'),
    'access callback' => TRUE,
    'type' => MENU_LOCAL_TASK,
    'weight' => -10,
  );
  $items['recommendations/recmd_cp/coursesinstr/update'] = array(
    'title' => 'Edit',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('recommends_cp_form_update'),
    'type' => MENU_LOCAL_TASK,
    'access callback' => TRUE,
    'weight' => -9,
  );
   $items['recommendations/recmd_cp/coursesinstr/delete'] = array(
    'title' => 'Delete',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('recommends_cp_form_delete'),
    'type' => MENU_LOCAL_TASK,
    'access callback' => TRUE,
    'weight' => -8,
  );
  
  $items['recommendations/recmd_cp/coursesinstr/help'] = array(
    'title' => 'Help',
    'page callback' => 'recommends_cp_advhelp',
    'type' => MENU_LOCAL_TASK,
    'access callback' => TRUE,
    'weight' => -7,
  );

  return $items;
}

/**
 * Render a list of entries in the database.
 */
function recommends_cp_list() {
  $output = '';

  // Get all entries in the recommends_cp table.
  if ($entries = recommends_cp_entry_load()) {
    $rows = array();
    foreach ($entries as $entry) {
      // Sanitize the data before handing it off to the theme layer.
      $rows[] = array_map('check_plain', (array) $entry);
    }
    // Make a table for them.
    $header = array(t('Id '), t('Email '),  t('Crs'),  t('Year'),  t('Gr '),  t(' Comments'));
    $output .= theme('table', array('header' => $header, 'rows' => $rows));
  }
  else {
    drupal_set_message(t('No entries have been added yet.'));
  }
  return $output;
}

/**
 * Prepare a simple form to add an entry, with all the interesting fields.
 */
function recommends_cp_form_add($form, &$form_state) {
  
  drupal_set_title('Add a Conducted Course');
  
  $form = array();
  
    $form = array(
    '#prefix' => '<div id="addform">',
    '#suffix' => '</div>',
  );
 
 $form['add'] = array(
    '#type'  => 'fieldset',
    '#title' => 'Professor: ' . variable_get('recommends_professor'),
  );
 $form['i_prof'] = array(
    '#type' => 'hidden',
    '#title' => t('*Professor Email'),
     '#disabled' => TRUE,
    '#size'  =>25,
    
     );
   $form['add']['i_course'] = array(
    '#type'  => 'textfield',
    '#title' => t('Course Number'),
    '#required'  => TRUE,
    '#size'  => 15,
  );
  $form['add']['i_semester'] = array(
    '#type' => 'select',
    '#title' => t('Semester '),
    '#size' => 1,
     '#options' => array(
    	'Fall' => t('Fall'), 
    	'Spring' => t('Spring'),
    	'Summer' => t('Summer'),
  ),
  );
   $form['add']['i_year'] = array(
    '#type'  => 'textfield',
    '#title' => t('Year'),
    '#required'  => TRUE,
    '#size'  => 15,
  );
   $form['add']['i_coursename'] = array(
    '#type'  => 'textfield',
    '#title' => t('Course Name'),
    '#size'  => 30,
  );
   $form['add']['i_objective'] = array(
      '#type'  => 'textarea',
  	  '#title' => t('Course Objective'),
    '#rows'  => 3,
    
  );
  
  $form['add']['i_grade_a'] = array(
      '#type'  => 'textarea',
  	  '#title' => t('Grade of A Commentary'),
    '#rows'  => 3,
    
  );
  $form['add']['i_grade_b'] = array(
      '#type'  => 'textarea',
  	  '#title' => t('Grade of B Commentary'),
    '#rows'  => 3,
    
  );
  $form['add']['i_grade_other'] = array(
      '#type'  => 'textarea',
  	  '#title' => t('General Grade Commentary'),
    '#rows'  => 3,
    
  );
  
  $form['add']['i_timestamp'] = array(
    '#type'  => 'textfield',
    '#title' => t('timestamp'),
    '#size'  => 20,
  );
  $form['add']['submit'] = array(
    '#type'  => 'submit',
    '#value' => t('Add'),
  );

  return $form;
}

/**
 * Submit handler for 'add entry' form.
 */
function recommends_cp_form_add_submit($form, $form_state){
  global $user;

  $format = variable_get('date_format_long', 'l, F j, Y - H:i');
  date_default_timezone_set('America/New_York');
  $date = date("c") ;
  $timestamp = substr($date,0,19);
  
  // Save the submitted entry.
  $entry = array(
    'i_prof'     => $form_state['values']['i_prof'],
	 'i_course'     => $form_state['values']['i_course'],
	 'i_semester'     => $form_state['values']['i_semester'],
    'i_year'     => $form_state['values']['i_year'],
    'i_coursename'     => $form_state['values']['i_coursename'],
    'i_objective'     => $form_state['values']['i_objective'],
    'i_grade_a'     => $form_state['values']['i_grade_a'],
    'i_grade_b'     => $form_state['values']['i_grade_other'],
    'i_grade_other'     => $form_state['values']['i_grade_a'],
    'i_prof'     => variable_get('recommends_professor_email'),
    'i_timestamp'     => $timestamp,
  );
  variable_set('recommends_course',$form_state['values']['i_course']);
    variable_set('recommends_semester',$form_state['values']['i_semester']);
    variable_set('recommends_year',$form_state['values']['i_year']);
  $return = recommends_cp_entry_insert($entry);
  if ($return) {
    
    drupal_set_message(t("Course entry created for professor  @entry ", array('@entry' => print_r($entry['i_prof'] . " - " . $entry['i_course']  . $entry['i_semester']  . " - " . $entry['i_year'], TRUE))));
    drupal_goto('recommendations/cplist/coursesinstr');
  }
}

/**
 * UI to update a record.
 */
function recommends_cp_form_update($form, &$form_state) {
  
  drupal_set_title('Courses Conducted - Edit');
  
  $courseinstr = variable_get('recommends_course');
  $semester = variable_get('recommends_semester');
  $year = variable_get('recommends_year');
  
  $courseinstr = str_replace( "_", " ", $courseinstr);
  
  $form = array(
    '#prefix' => '<div id="updateform">',
    '#suffix' => '</div>',
  );

  $entry = array();
  $entries = recommends_cp_entry_load_mob($entry,$courseinstr,$semester,$year);
  
  $keyed_entries = array();
  if (empty($entries)) {
    $form['no_values'] = array(
      '#value' => t("No entries exist in the table recommends_cp table."),
    );
    return $form;
  }

  foreach ($entries as $entry) {
    $options[$entry->i_pid] = t("@i_course - @i_coursename, @i_semester, @i_year", array(
    '@i_pid' => $entry->i_pid,
    '@i_prof' => $entry->i_prof,
    '@i_course' => $entry->i_course,
    '@i_semester' => $entry->i_semester,
    '@i_year' => $entry->i_year,
     '@i_coursename' => $entry->i_coursename,
     '@i_objective' => $entry->i_objective,
     '@i_grade_a' => $entry->i_grade_a,
     '@i_grade_b' => $entry->i_grade_b,
     '@i_grade_other' => $entry->i_grade_other,
     '@i_timestamp' => $entry->i_timestamp
    ));
    $keyed_entries[$entry->i_pid] = $entry;
  }
  $default_entry = !empty($form_state['values']['i_pid']) ? $keyed_entries[$form_state['values']['i_pid']] : $entries[0];

  $form_state['entries'] = $keyed_entries;

  $form['edit'] = array(
    '#type'  => 'fieldset',
    '#title' => variable_get('recommends_professor'),
    '#prefix' => '<div id="formlimit">',
    '#suffix' => '</div>',
  );
 
   $form['i_pid'] = array(
    '#type' => 'hidden',
    '#title' => t('pid'),
    '#size' => 25,
    '#default_value' => $default_entry->i_pid,
  );

  $form['i_prof'] = array(
    '#type' => 'hidden',
    '#title' => t('Professor Email'),
    '#size' => 25,
    '#default_value' => $default_entry->i_prof,
  );
    $form['i_course'] = array(
    '#type' => 'textfield',
    '#title' => t('Course Number'),
    '#size' => 15,
    '#default_value' => $default_entry->i_course,
  );
  $form['i_semester'] = array(
    '#type' => 'select',
    '#title' => t('Semester '),
    '#size' => 1,
     '#options' => array(
    	'Fall' => t('Fall'), 
    	'Spring' => t('Spring'),
    	'Summer' => t('Summer'),
  ),
  );
   $form['i_year'] = array(
    '#type' => 'textfield',
    '#title' => t('Year'),
    '#size' => 10,
    '#default_value' => $default_entry->i_year,
  );
   $form['i_coursename'] = array(
      '#type'  => 'textfield',
  	  '#title' => t('Course Name'),
    '#size'  => 30,
    '#default_value' => $default_entry->i_coursename,
  );
  $form['i_objective'] = array(
      '#type'  => 'textarea',
  	  '#title' => t('Course Objective'),
    '#rows'  => 3,
    '#default_value' => $default_entry->i_objective,
  );
  
  $form['i_grade_a'] = array(
      '#type'  => 'textarea',
  	  '#title' => t('Grade of A Commentary'),
    '#rows'  => 3,
    '#default_value' => $default_entry->i_grade_a,
  );
  $form['i_grade_b'] = array(
      '#type'  => 'textarea',
  	  '#title' => t('Grade of B Commentary'),
    '#rows'  => 3,
    '#default_value' => $default_entry->i_grade_b,
  );
  $form['i_grade_other'] = array(
      '#type'  => 'textarea',
  	  '#title' => t('General Grade Commentary'),
    '#rows'  => 3,
    '#default_value' => $default_entry->i_grade_other,
  );
  $form['i_timestamp'] = array(
    '#type' => 'textfield',
    '#title' => t('Timestamp'),
    '#size' => 20,
    '#default_value' => $default_entry->i_timestamp,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save'),
  );
  return $form;
}
/******************************************************************
 * UI to view a record.
 *******************************************************************/
function recommends_cp_form_view($form, &$form_state,$courseinstr=NULL,$semester=NULL,$year=NULL) {
  
  drupal_set_title('Courses Conducted - View');
  
  if (!empty($courseinstr)) {
    
    variable_set('recommends_course',$courseinstr);
    variable_set('recommends_semester',$semester);
    variable_set('recommends_year',$year);
    
  } else {
      $courseinstr = variable_get('recommends_course');
      $semester = variable_get('recommends_semester');
      $year = variable_get('recommends_year');
  }
  
  $courseinstr = str_replace( "_", " ", $courseinstr);
  
  $form = array(
    '#prefix' => '<div id="viewform">',
    '#suffix' => '</div>',
  );

  $entry = array();
  $entries = recommends_cp_entry_load_mob($entry,$courseinstr,$semester,$year);
 /* 
  $msg = "(517)This is entries - ";
    drupal_set_message('<pre>' . print_r($msg, TRUE)  . print_r($entries, TRUE) . '</pre>');
 */
  $keyed_entries = array();
  if (empty($entries)) {
    $form['no_values'] = array(
      '#value' => t("No entries exist in the table recommends_cp table."),
    );
    return $form;
  }

  foreach ($entries as $entry) {
    $options[$entry->i_pid] = t("@i_course - @i_coursename, @i_semester, @i_year", array(
    '@i_pid' => $entry->i_pid, 
    '@i_course' => $entry->i_course,
    '@i_coursename' => $entry->i_coursename,
    '@i_objective' => $entry->i_objective,
    '@i_grafe_a' => $entry->i_grade_a,
    '@i_grafe_b' => $entry->i_grade_b,
    '@i_grafe_other' => $entry->i_grade_other,
    '@i_semester' => $entry->i_semester,
    '@i_year' => $entry->i_year,
     '@i_timestamp' => $entry->i_timestamp
    ));
    $keyed_entries[$entry->i_pid] = $entry;
  }
  $default_entry = !empty($form_state['values']['i_pid']) ? $keyed_entries[$form_state['values']['i_pid']] : $entries[0];
  
  $form_state['entries'] = $keyed_entries;
  
   $form['view'] = array(
    '#type'  => 'fieldset',
    '#title' => variable_get('recommends_professor'), 
  );
  $form['view']['i_pid'] = array(
    '#type' => 'select',
    '#options' => $options,
    '#default_value' => $default_entry->i_pid,
    '#ajax' => array(
      'wrapper' => 'viewform',
      'callback' => 'recommends_cp_form_view_callback',
    ),
  );
   $form['view']['i_pid'] = array(
    '#type' => 'hidden',
    '#title' => t('pid'),
    '#size' => 25,
    '#disabled' => TRUE,
    '#default_value' => $default_entry->i_pid,
  );

  $form['view']['i_prof'] = array(
    '#type' => 'hidden',
    '#title' => t('Professor Email'),
    '#size' => 25,
    '#disabled' => TRUE,
    '#default_value' => $default_entry->i_prof,
  );
   $form['view']['i_course'] = array(
    '#type' => 'textfield',
    '#title' => t('Course Number'),
    '#size' => 15,
    '#disabled' => TRUE,
    '#default_value' => $default_entry->i_course,
  );
  
   $form['view']['i_semester'] = array(
    '#type' => 'textfield',
    '#title' => t('Semester'),
    '#size' => 6,
    '#disabled' => TRUE,
    '#default_value' => $default_entry->i_semester,
  );
   $form['view']['i_year'] = array(
    '#type' => 'textfield',
    '#title' => t('Year'),
    '#size' => 10,
    '#disabled' => TRUE,
    '#default_value' => $default_entry->i_year,
  );
   $form['view']['i_coursename'] = array(
      '#type'  => 'textfield',
  	  '#title' => t('Course Name'),
    '#size'  => 25,
    '#disabled' => TRUE,
    '#default_value' => $default_entry->i_coursename,
  );
  $form['view']['i_objective'] = array(
      '#type'  => 'textarea',
  	  '#title' => t('Course Objective'),
    '#rows'  => 3,
    '#cols'  => 25,
    '#resizable'  => TRUE,
    '#disabled' => TRUE,
    '#default_value' => $default_entry->i_objective,
  );
  $form['view']['i_grade_a'] = array(
      '#type'  => 'textarea',
  	  '#title' => t('Grade A Commentary'),
    '#rows'  => 3,
    '#disabled' => TRUE,
    '#default_value' => $default_entry->i_grade_a,
  );
  $form['view']['i_grade_b'] = array(
      '#type'  => 'textarea',
  	  '#title' => t('Grade B Commentary'),
    '#rows'  => 3,
    '#disabled' => TRUE,
    '#default_value' => $default_entry->i_grade_b,
  );  
  $form['view']['i_grade_other'] = array(
      '#type'  => 'textarea',
  	  '#title' => t('General Grade Commentary'),
    '#rows'  => 3,
    '#disabled' => TRUE,
    '#default_value' => $default_entry->i_grade_other,
  );
  $form['view']['i_timestamp'] = array(
    '#type' => 'textfield',
    '#title' => t('Timestamp'),
    '#size' => 20,
    '#disabled' => TRUE,
    '#default_value' => $default_entry->i_timestamp,
  );

  $form['view']['submit'] = array(
    '#type' => 'hidden',
    '#value' => t('View'),
  );
  return $form;
}

/******************************************************************
 * UI to delete a record.
 *******************************************************************/
function recommends_cp_form_delete($form, &$form_state) {
  
  drupal_set_title('Courses Coducted - Delete');
  
  $courseinstr = variable_get('recommends_course');
  $semester = variable_get('recommends_semester');
  $year = variable_get('recommends_year');
  
  $courseinstr = str_replace( "_", " ", $courseinstr);
  
  $form = array(
    '#prefix' => '<div id="deleteform">',
    '#suffix' => '</div>',
  );

  $entry = array();
  $entries = recommends_cp_entry_load_mob($entry,$courseinstr,$semester,$year);;
  $keyed_entries = array();
  if (empty($entries)) {
    $form['no_values'] = array(
      '#value' => t("No entries exist in the table recommends_cp table."),
    );
    return $form;
  }

  foreach ($entries as $entry) {
    $options[$entry->i_pid] = t("@i_course - @i_coursename, @i_semester, @i_year", array(
    '@i_pid' => $entry->i_pid, 
    '@i_prof' => $entry->i_prof,
    '@i_course' => $entry->i_course,
    '@i_semester' => $entry->i_semester,
    '@i_year' => $entry->i_year,
     '@i_coursename' => $entry->i_coursename,
     '@i_objective' => $entry->i_objective,
     '@i_grade_a' => $entry->i_grade_a,
     '@i_grade_b' => $entry->i_grade_b,
     '@i_grade_other' => $entry->i_grade_other,
     '@i_timestamp' => $entry->i_timestamp
    ));
    $keyed_entries[$entry->i_pid] = $entry;
  }
  $default_entry = !empty($form_state['values']['i_pid']) ? $keyed_entries[$form_state['values']['i_pid']] : $entries[0];

  $form_state['entries'] = $keyed_entries;

  
  $form['pcdelete'] = array(
    '#type'  => 'fieldset',
    '#title' => variable_get('recommends_professor'),
    '#prefix' => '<div id="formlimit">',
    '#suffix' => '</div>',
  );
  
  $form['delete']['i_pid'] = array(
    '#type' => 'hidden',
    '#title' => t('pid'),
    '#size' => 25,
    '#disabled' => TRUE,
    '#default_value' => $default_entry->i_pid,
  );

  $form['delete']['i_prof'] = array(
    '#type' => 'hidden',
    '#title' => t('Professor Email'),
    '#size' => 25,
    '#disabled' => TRUE,
    '#default_value' => $default_entry->i_prof,
  );
   $form['delete']['i_course'] = array(
    '#type' => 'textfield',
    '#title' => t('Course Number'),
    '#size' => 15,
    '#disabled' => TRUE,
    '#default_value' => $default_entry->i_course,
  );
   $form['delete']['i_semester'] = array(
    '#type' => 'textfield',
    '#title' => t('Semester'),
    '#size' => 6,
    '#disabled' => TRUE,
    '#default_value' => $default_entry->i_semester,
  );
   $form['delete']['i_year'] = array(
    '#type' => 'textfield',
    '#title' => t('Year'),
    '#size' => 10,
    '#disabled' => TRUE,
    '#default_value' => $default_entry->i_year,
  );
   $form['delete']['i_coursename'] = array(
      '#type'  => 'textfield',
  	  '#title' => t('Course Name'),
    '#size'  => 30,
    '#disabled' => TRUE,
    '#default_value' => $default_entry->i_coursename,
  );
  
   $form['delete']['i_objective'] = array(
      '#type'  => 'textarea',
  	  '#title' => t('CourseObjective'),
    '#rows'  => 3,
    '#disabled' => TRUE,
    '#default_value' => $default_entry->i_objective,
  );
   $form['delete']['i_grade_a'] = array(
      '#type'  => 'textarea',
  	  '#title' => t('Grade of A Commentary'),
    '#rows'  => 3,
    '#disabled' => TRUE,
    '#default_value' => $default_entry->i_grade_a,
  );
  $form['delete']['i_grade_b'] = array(
      '#type'  => 'textarea',
  	  '#title' => t('Grade of B Commentary'),
    '#rows'  => 3,
    '#disabled' => TRUE,
    '#default_value' => $default_entry->i_grade_b,
  );
  $form['delete']['i_grade_other'] = array(
      '#type'  => 'textarea',
  	  '#title' => t('General Grade Commentary'),
    '#rows'  => 3,
    '#disabled' => TRUE,
    '#default_value' => $default_entry->i_grade_other,
  );
  
  $form['delete']['i_timestamp'] = array(
    '#type' => 'textfield',
    '#title' => t('Timestamp'),
    '#size' => 20,
    '#disabled' => TRUE,
    '#default_value' => $default_entry->i_timestamp,
  );

  $form['delete']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Delete'),
  );
  return $form;
}

/**
 * AJAX callback handler for the i_pid select.
 *
 * When the i_pid changes, populates the defaults from the database in the form.
 */
function recommends_cp_form_update_callback($form, $form_state) {
  $entry = $form_state['entries'][$form_state['values']['i_pid']];
  // Setting the #value of items is the only way I was able to figure out
  // to get replaced defaults on these items. #default_value will not do it
  // and shouldn't.
  foreach (array( 'i_prof', 'i_course', 'i_semester', 'i_year', 'i_coursename', 'i_objective', 'i_grade_a', 'i_grade_b', 'i_grade_other','i_timestamp') as $item) {
    $form[$item]['#value'] = $entry->$item;
  }
  return $form;
}
function recommends_cp_form_add_callback($form, $form_state) {
  $entry = $form_state['entries'][$form_state['values']['i_pid']];
  // Setting the #value of items is the only way I was able to figure out
  // to get replaced defaults on these items. #default_value will not do it
  // and shouldn't.
  foreach (array( 's_email') as $item) {
    $form[$item]['#value'] = $entry->$item;
  }
  return $form;
}

/**
 * Submit handler for 'update entry' form.
 */
function recommends_cp_form_update_submit($form, $form_state){
  global $user;
  
  $format = variable_get('date_format_long', 'l, F j, Y - H:i');
  date_default_timezone_set('America/New_York');
  $date = date("c") ;
  $timestamp = substr($date,0,19);

  // Save the submitted entry.
  $entry = array(
    'i_pid' => $form_state['values']['i_pid'],
     'i_prof' => $form_state['values']['i_prof'],
    'i_course' => $form_state['values']['i_course'],
    'i_semester' => $form_state['values']['i_semester'],
     'i_year' => $form_state['values']['i_year'],
     'i_coursename' => $form_state['values']['i_coursename'],
     'i_objective' => $form_state['values']['i_objective'],
     'i_grade_a' => $form_state['values']['i_grade_a'],
     'i_grade_b' => $form_state['values']['i_grade_b'],
     'i_grade_other' => $form_state['values']['i_grade_other'],
     'i_timestamp' => $timestamp,
  );
  $count = recommends_cp_entry_update($entry);
  drupal_set_message(t("Course entry updated for professor  @entry ", array('@entry' => print_r($entry['i_prof'] . " - " . $entry['i_course']  . $entry['i_semester'] . " - " . $entry['i_year'], TRUE))));
  drupal_goto('recommendations/cplist/coursesinstr');

}
/*************************************************************
*
**************************************************************/
function recommends_cp_form_view_callback($form, $form_state) {
  $entry = $form_state['entries'][$form_state['values']['i_pid']];
  // Setting the #value of items is the only way I was able to figure out
  // to get replaced defaults on these items. #default_value will not do it
  // and shouldn't.
  foreach (array('i_pid',  'i_course', 'i_semester', 'i_year', 'i_coursename', 'i_objective', 'i_grade_a', 'i_grade_b', 'i_grade_other', 'i_timestamp') as $item) {
    $form[$item]['#value'] = $entry->$item;
  }
  return $form;
}

/*************************************************************
 * Submit handler for 'view entry' form.
 ***************************************************************/
function recommends_cp_form_view_submit($form, $form_state){
  global $user;

  // Save the submitted entry.
  $entry = array(
    'i_pid' => $form_state['values']['i_pid'],
    'i_course' => $form_state['values']['i_course'],
    'i_semester' => $form_state['values']['i_semester'],
     'i_year' => $form_state['values']['i_year'],
     'i_coursename' => $form_state['values']['i_coursename'],
     'i_objective' => $form_state['values']['i_objective'],
     'i_grade_a' => $form_state['values']['i_grade_a'],
     'i_grade_b' => $form_state['values']['i_grade_b'],
     'i_grade_other' => $form_state['values']['i_other'],
     'i_timestamp' => $form_state['values']['i_timestamp'],
  );
  $count = recommends_cp_entry_view($entry);
   drupal_set_message(t("Course entry for professor  @entry ", array('@entry' => print_r($entry['icourse'] . " - " . $entry['i_coursename']  . $entry['i_semester'] . " - " . $entry['i_year'], TRUE))));
}
/*************************************************************
*
**************************************************************/
function recommends_cp_form_delete_callback($form, $form_state) {
  $entry = $form_state['entries'][$form_state['values']['i_pid']];
  // Setting the #value of items is the only way I was able to figure out
  // to get replaced defaults on these items. #default_value will not do it
  // and shouldn't.
  foreach (array('i_pid', 'i_prof', 'i_course', 'i_semester', 'i_year',  'i_coursename', 'i_objective', 'i_grade_a', 'i_grade_b', 'i_grade_other', 'i_timestamp') as $item) {
    $form[$item]['#value'] = $entry->$item;
  }
  return $form;
}

/*************************************************************
 * Submit handler for 'delete entry' form.
 ***************************************************************/
function recommends_cp_form_delete_submit($form, $form_state){
  global $user;

  // Save the submitted entry.
  $entry = array(
    'i_pid' => $form_state['values']['i_pid'],
     'i_prof' => $form_state['values']['i_prof'],
    'i_course' => $form_state['values']['i_course'],
    'i_semester' => $form_state['values']['i_semester'],
     'i_year' => $form_state['values']['i_year'],
     'i_coursename' => $form_state['values']['i_coursename'],
     'i_objective' => $form_state['values']['i_objective'],
     'i_grade_a' => $form_state['values']['i_grade_a'],
     'i_grade_b' => $form_state['values']['i_grade_b'],
     'i_grade_other' => $form_state['values']['i_grade_other'],
     'i_timestamp' => $form_state['values']['i_timestamp'],
  );
  $count = recommends_cp_entry_delete($entry);
   drupal_set_message(t("Deeleted course entry for professor  @entry ", array('@entry' => print_r($entry['i_prof'] . " - " . $entry['i_course'] . $entry['i_semester']  . " - " . $entry['i_year'], TRUE))));
   drupal_goto('recommendations/cplist/coursesinstr');
   
}

/*************************************************************
 *    Display help page
 ***************************************************************/
function recommends_cp_advhelp(){
  drupal_set_title('Conducted Courses - Help');

  
  $module = 'recommendations';
  $topic = 'using-prof-conducted';
  $type = 'title';
  
  $output = theme('advanced_help_topic', array(
  'module' => $module, 
  'topic' => $topic,
  'type' => $type,
  ));
  
  return $output;
}  